services:
  blog:
    container_name: blog
#    image: ghcr.io/toshibe678/blog.toshi.click/blog:latest
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ./blog:/app
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    tty: true

