name: Run lint

on: [push]

jobs:

  front_build:
    # 実行するインスタンス
    runs-on: ubuntu-latest
    # nodeのバージョン一覧
    strategy:
      matrix:
        node-version: ['18.x']
    # 各ステップの実行定義
    steps:
      # チェックアウト
      - uses: actions/checkout@v1

      # 使用するnodeのバージョンを指定
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # パッケージのインストール
      - name: yarn install
        run: yarn --cwd ./blog install

      # Lint
      - name: lint
        run: yarn --cwd ./blog lint
